[tox]
envlist =
    py{310,311,312,313,314}-pytracking,
    py{310,311,312,313,314}-django-dj52,
    py{312,313,314}-django-dj60

[testenv]
extras =
    test
    pytracking: crypto
    pytracking: html
    pytracking: webhook
    django:     django
commands =
    pytracking:  pytest --ignore tests/test_django.py
    django:      pytest tests/test_django.py
deps=
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.1
