name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            toxenv: py310-pytracking
          - python-version: "3.11"
            toxenv: py311-pytracking
          - python-version: "3.12"
            toxenv: py312-pytracking
          - python-version: "3.13"
            toxenv: py313-pytracking
          - python-version: "3.14"
            toxenv: py314-pytracking
          - python-version: "3.10"
            toxenv: py310-django-dj52
          - python-version: "3.11"
            toxenv: py311-django-dj52
          - python-version: "3.12"
            toxenv: py312-django-dj52
          - python-version: "3.13"
            toxenv: py313-django-dj52
          - python-version: "3.14"
            toxenv: py314-django-dj52
          - python-version: "3.12"
            toxenv: py312-django-dj60
          - python-version: "3.13"
            toxenv: py313-django-dj60
          - python-version: "3.14"
            toxenv: py314-django-dj60
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox
        run: tox -e ${{ matrix.toxenv }}
